create table if not exists public.portfolio_content (
    id integer primary key check (id = 1),
    content jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.portfolio_content enable row level security;

drop policy if exists "Public can read portfolio" on public.portfolio_content;
create policy "Public can read portfolio"
    on public.portfolio_content for select
    using (true);

drop policy if exists "Authenticated admin can write portfolio" on public.portfolio_content;
create policy "Authenticated admin can write portfolio"
    on public.portfolio_content for all
    to authenticated
    using ((auth.jwt() ->> 'email') = 'gamerhindi571@gmail.com')
    with check ((auth.jwt() ->> 'email') = 'gamerhindi571@gmail.com');

create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can send contact messages" on public.contact_messages;
create policy "Anyone can send contact messages"
    on public.contact_messages for insert
    to anon, authenticated
    with check (true);

drop policy if exists "Admin can read contact messages" on public.contact_messages;
create policy "Admin can read contact messages"
    on public.contact_messages for select
    to authenticated
    using ((auth.jwt() ->> 'email') = 'gamerhindi571@gmail.com');

drop policy if exists "Admin can delete contact messages" on public.contact_messages;
create policy "Admin can delete contact messages"
    on public.contact_messages for delete
    to authenticated
    using ((auth.jwt() ->> 'email') = 'gamerhindi571@gmail.com');

insert into public.portfolio_content (id, content)
values (1, '{
  "siteName": "Khandker Sadman Rafid Saad",
  "heroName": "Khandker Sadman Rafid Saad",
  "heroBio": "A dedicated professional blending operations management with a passion for digital content and community service.",
  "projectCategory": "Digital Content Creation",
  "projectTitle": "Educational Digitization",
  "projectDescription": "Digitized and systematically formatted complex educational questionnaires into high-quality, engaging presentations. This project involved converting raw data into visually digestible formats, ensuring accuracy, and enhancing the learning experience for end-users.",
  "email": "ksrafid@example.com",
  "linkedin": "https://linkedin.com/in/ksrafid"
}'::jsonb)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('portfolio-assets', 'portfolio-assets', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view portfolio assets" on storage.objects;
create policy "Public can view portfolio assets"
    on storage.objects for select
    using (bucket_id = 'portfolio-assets');

drop policy if exists "Admin can upload portfolio assets" on storage.objects;
create policy "Admin can upload portfolio assets"
    on storage.objects for all
    to authenticated
    using (bucket_id = 'portfolio-assets' and (auth.jwt() ->> 'email') = 'gamerhindi571@gmail.com')
    with check (bucket_id = 'portfolio-assets' and (auth.jwt() ->> 'email') = 'gamerhindi571@gmail.com');
